server:
  port: 9196
spring:
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  application:
    name: salary-service
logging:
  file: C:/Users/vidula/Desktop/oms.log

bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000